image:
    - Visual Studio 2022  
    - Visual Studio 2019  
    - Visual Studio 2017    


init:
    - git config --global core.autocrlf input

clone_folder: c:\projects\cc.ublox.commsdsl
shallow_clone: true             

platform:
    - x64
    - x86

configuration:
    - Debug
    - Release

environment:
    COMMS_BRANCH: master
    COMMSDSL_BRANCH: master
    CC_TOOLS_QT_BRANCH: master
    matrix:
        - CPP_STD: 11
        - CPP_STD: 14
        - CPP_STD: 17
        - CPP_STD: 20

matrix:
    fast_finish: false
    exclude:
        - image: Visual Studio 2017
          CPP_STD: 20                           
        
install:
    - call script\appveyor_install.bat
    - set PATH=%PATH%;%QTDIR%\bin
    - set BUILD_DIR=%APPVEYOR_BUILD_FOLDER%\build.%PLATFORM%.%CONFIGURATION%.%TOOLCHAIN%
    - if exist %BUILD_DIR% rmdir /S /Q %BUILD_DIR%
    - set COMMS_TAG=%COMMS_BRANCH%
    - set COMMSDSL_TAG=%COMMSDSL_BRANCH%
    - set CC_TOOLS_QT_TAG=%CC_TOOLS_QT_BRANCH%
    - set COMMON_INSTALL_DIR=%BUILD_DIR%\install
    - set COMMON_BUILD_TYPE=%CONFIGURATION%
    - set COMMON_CXX_STANDARD=%CPP_STD%
    - call script\prepare_externals.bat

build_script:
    - echo ------------------------- Building Project -------------------------
    - cd %BUILD_DIR%
    - cmake .. -DCMAKE_BUILD_TYPE=%CONFIGURATION% -G "NMake Makefiles" -DBOOST_ROOT="%BOOST_DIR%" -DBoost_USE_STATIC_LIBS=ON -DCMAKE_INSTALL_PREFIX="%COMMON_INSTALL_DIR%" -DCMAKE_PREFIX_PATH="%COMMON_INSTALL_DIR%" -DCMAKE_CXX_STANDARD=%CPP_STD% -DUBLOX_BUILD_GEN_PROTOCOL=ON -DUBLOX_BUILD_GEN_TEST=ON -DUBLOX_BUILD_GEN_TOOLS=ON
    - cmake --build .  --config %CONFIGURATION% --target install



